version: 0.0
os: linux
files:
  - source: webapp/CloudWebApp/target/CloudAssignment1-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps
hooks:
  AfterInstall:
   - location: ./scripts/afterInstall.sh
     timeout: 180
     runas: centos
